<?php $view->extend('layout.phtml') ?>

<div class="row">
    <div class="span6">
        <p>
            Kickstart a Silex project with this easy start.
        </p>
        <ul class="unstyled">
            <li><i class="icon-check"></i> <a href="http://www.php.net">PHP 5.3</a></li>
            <li><i class="icon-check"></i> <a href="http://silex.sensiolabs.org/">Silex Microframework</a></li>
            <li><i class="icon-check"></i> <a href="http://symfony.com/doc/current/components/templating.html">Symfony Templating Component</a></li>
            <li><i class="icon-check"></i> <a href="http://www.doctrine-project.org/projects/orm.html">Doctrine 2 ORM</a></li>
            <li><i class="icon-check"></i> <a href="http://twitter.github.com/bootstrap">Twitter Bootstrap</a> + <a href="http://fortawesome.github.com/Font-Awesome/">Font Awesome</a></li>
        </ul>
    </div>
    <div class="span6">
        <div class="hero-unit">
            <h1>Barebones Silex Application</h1>
            <hr/>
            <h2 style="margin-top:20px;">with PhpEngine templating</h2>
        </div>
    </div>
</div>
