<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Silex Barebones App</title>
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <style type="text/css">
        <!--
        body { margin-top: 40px; }
        -->
        </style>
    </head>
    <body>
        <div class="container">
            <?php $view['slots']->output('_content') ?>
        </div>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </body>
</html>
